# Generated by Django 3.2.12 on 2022-02-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_news_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
