# Generated by Django 3.2.12 on 2022-02-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20220226_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthplace',
            name='State',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='birthplace',
            name='city',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(max_length=250),
        ),
    ]
