# Generated by Django 3.2.12 on 2022-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20220226_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='item.Product'),
        ),
    ]
