# Generated by Django 3.2.12 on 2022-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('head', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
