# Generated by Django 3.2.12 on 2022-02-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloapp', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('price', models.IntegerField()),
                ('offer', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
