# Generated by Django 3.2.12 on 2022-02-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloapp', '0003_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='places',
            name='offer',
            field=models.IntegerField(),
        ),
    ]
